/**
 * translations.ts - Internationalization (i18n) Translations
 * 
 * This file contains all text content for the portfolio site in multiple languages.
 * Currently supports: English (en) and Spanish (es)
 */

export type Language = 'en' | 'es';

export interface Translations {
  nav: {
    about: string;
    experience: string;
    projects: string;
    contact: string;
  };
  hero: {
    greeting: string;
    name: string;
    title: string;
    tagline: string;
    downloadCV: string;
    getInTouch: string;
    viewWork: string;
    downloadEnglish: string;
    downloadSpanish: string;
  };
  about: {
    heading: string;
    paragraphs: string[];
  };
  experience: {
    heading: string;
    jobs: Array<{
      role: string;
      company: string;
      duration: string;
      description: string;
    }>;
  };
  portfolio: {
    heading: string;
    viewDetails: string;
    projects: Array<{
      title: string;
      company: string;
      description: string;
      detailContent?: string;
    }>;
  };
  footer: {
    heading: string;
    subheading: string;
    legalNotice: string;
    copyright: string;
    legalModal: {
      owner: string;
      legalStatus: string;
      legalStatusText: string;
      vatNumber: string;
      taxCode: string;
      registeredOffice: string;
      registeredOfficeText: string;
      contact: string;
      contactEmail: string;
      privacy: string;
      privacyText: string;
    };
  };
  skills: {
    [key: string]: {
      name: string;
      description: string;
    };
  };
}

export const translations: Record<Language, Translations> = {
  en: {
    nav: {
      about: 'About',
      experience: 'Experience',
      projects: 'Projects',
      contact: 'Contact',
    },
    hero: {
      greeting: 'Hi, I\'m',
      name: 'Francisco Perez Leiros',
      title: 'Software QA Test Engineer',
      tagline: 'Specializing in Test Automation, CI/CD, AI integration, and Quality Assurance for web, mobile, cloud, and industrial systems.',
      downloadCV: 'Download CV',
      getInTouch: 'Get in Touch',
      viewWork: 'View My Work',
      downloadEnglish: 'English Version',
      downloadSpanish: 'Spanish Version',
    },
    about: {
      heading: 'About Me',
      paragraphs: [
        'Automation QA Engineer with 5+ years of experience across web, mobile, cloud, and industrial automation systems. Strong background in manual testing foundations, with a clear progression into test automation, CI/CD integration, and system-level quality assurance.',
        'Currently working as a Software Quality Assurance Test Engineer at Tetra Pak, performing Verification & Validation (V&V) of industrial automation solutions using Beckhoff and TwinCAT PLCs. My work includes system-level testing on cloud-deployed Linux (CentOS) environments, validating functional and safety requirements, and analyzing SQL-based logs to support root cause analysis and defect resolution.',
        'Previously at Cemantica, I owned the end-to-end QA process and built automation frameworks using Playwright (including MCP) with TypeScript, fully integrated into Azure DevOps CI/CD pipelines. This enabled automated regression testing and improved release reliability.',
        'Earlier in my career, I built strong QA fundamentals through hands-on manual, API, and cross-platform testing across web and mobile applications, working in Agile/Scrum environments and collaborating closely with developers and product teams.',
      ],
    },
    experience: {
      heading: 'Professional Experience',
      jobs: [
        {
          role: 'Quality Assurance Test Specialist',
          company: 'Tetrapak - Modena, Italy',
          duration: '11/2024 - 11/2025',
          description: 'Performed Verification and Validation (V&V) of test plans and authored comprehensive test cases for industrial automation systems using Beckhoff and TwinCAT PLCs, with test cases written in Gherkin (BDD) for clear, behavior-driven specifications. Conducted system testing deployed using Docker across Cloud platforms on Linux CentOS-based environments, ensuring compliance with functional and safety requirements. Analysed and interpreted SQL-based log data generated by automation systems to verify system behaviour, troubleshoot issues, and support root cause analysis.',
        },
        {
          role: 'Quality Assurance Specialist',
          company: 'Cemantica - Paris, France',
          duration: '12/2023 - 11/2024',
          description: 'Managed the full QA process, including the development of comprehensive test suites and the execution of functional, regression, and integration tests. Engineered a test automation framework from scratch using TypeScript and Playwright, integrated directly into Azure DevOps pipelines for automated runs. Also used GitHub and GitHub Actions. Executed a hybrid testing strategy, utilizing automated scripts for regression while performing manual testing for edge cases and UI/UX validation. Acted as the primary technical point of contact for defect resolution, debugging to assist the development team in fixing high-priority bugs.',
        },
        {
          role: 'QA Engineer',
          company: 'Tudip Technologies - Pune, India',
          duration: '03/2022 - 12/2023',
          description: 'Reviewed functional and design specifications to align testing objectives with project requirements. Developed and executed detailed test cases for various functionalities across web and mobile platforms (iOS & Android). Collaborated with a Senior QA Engineer to design and develop test cases using Gherkin (BDD) and Selenium with Python, integrating them into a Jenkins CI pipeline. Performed diverse testing types, including functional, regression, integration, and accessibility testing. Used Postman for comprehensive REST API testing. Mentored new hires, leading multiple onboarding processes.',
        },
        {
          role: 'QA Tester',
          company: 'UTest - Massachusetts, United States',
          duration: '11/2020 - 03/2022',
          description: 'Conducted manual testing of web-based platforms, developing detailed test plans and cases. Performed functional, regression, integration, and user acceptance testing to ensure platform stability. Collaborated with teams to validate new features and identify critical bugs.',
        },
      ],
    },
    portfolio: {
      heading: 'Featured Projects',
      viewDetails: 'View full details',
      projects: [
        {
          title: 'Software Quality Assurance Test Engineer',
          company: 'Tetra Pak',
          description: 'Performed Verification & Validation for industrial automation systems using Beckhoff PLCs, including system-level testing on cloud-deployed Linux environments and SQL-based log analysis for root cause resolution.',
          detailContent: `# Software Quality Assurance Test Engineer – Tetra Pak (Contract)

**Period:** Nov 2024 – Nov 2025 (1 yr 1 mo)  
**Location:** Modena, Emilia-Romagna, Italy · Hybrid  
**Role Type:** Contract

---

## Role Overview
As a **Software Quality Assurance Test Engineer** at **Tetra Pak**, I worked on industrial automation and cloud-based systems, focusing on **Verification & Validation (V&V)**, system-level testing, and data-driven quality analysis in complex, safety-critical environments.

---

## Key Responsibilities & Contributions

- 🏭 Performed **Verification & Validation (V&V)** for industrial automation systems using **Beckhoff PLCs and TwinCAT**, ensuring compliance with functional and safety requirements
- 🧪 Authored and executed **system-level test cases** covering control logic, system integrations, and edge-case scenarios
- ☁️ Conducted **system testing on cloud-deployed Linux (CentOS) environments**, validating stability, reliability, and real-world operational behavior
- 🗄️ Analyzed **SQL-based log data** to verify system behavior, support root cause analysis, and speed up defect resolution
- 🔗 Collaborated closely with **cross-functional engineering teams** using **Azure DevOps** for defect tracking, test execution, and continuous quality improvement

---

## Tools & Technologies

- **Industrial Automation:** Beckhoff PLC, TwinCAT
- **Cloud & Infrastructure:** Microsoft Azure, Docker, Linux (CentOS)
- **Data & Analysis:** SQL
- **QA & ALM:** Azure DevOps
- **Testing Practices:** Test Planning, Test Design, Integration & System Testing

---

## Skills & Competencies

- Verification & Validation (V&V)
- System & Integration Testing
- Industrial Automation QA
- Cloud-Based System Testing
- Log Analysis & Root Cause Investigation
- Cross-Functional Collaboration
- Quality Assurance in Safety-Critical Systems

---

## Impact
This role strengthened my expertise in **industrial and system-level quality assurance**, bridging software, cloud infrastructure, and automation systems to ensure reliability, safety, and traceability in production-critical environments.`,
        },
        {
          title: 'Quality Assurance Specialist',
          company: 'Cemantica',
          description: 'Designed and implemented automated test frameworks using Playwright with TypeScript, built a complete CI/CD pipeline from scratch integrated with Azure DevOps, enabling automated test execution within the delivery pipeline.',
          detailContent: `# Quality Assurance Specialist – Cemantica (Contract)

**Period:** Dec 2023 – Nov 2024 (1 yr)  
**Location:** Levallois-Perret, Île-de-France, France · Remote  
**Role Type:** Contract

---

## Role Overview
As a **Quality Assurance Specialist** at **Cemantica**, I owned the complete QA lifecycle for the product, combining strong test strategy ownership with hands-on automation, CI/CD integration, and manual testing to ensure consistent quality across releases.

---

## Key Responsibilities & Contributions

- 🧠 Owned the **end-to-end QA process**, including test strategy definition, planning, execution, and release validation
- 🤖 Designed and implemented **automated test frameworks** using **Playwright with TypeScript**, significantly increasing regression test coverage
- 🚀 Built a **CI/CD pipeline from scratch** integrated with **Azure DevOps**, enabling automated test execution within the delivery pipeline
- 🧪 Performed **manual and exploratory testing** to complement automation and identify edge-case defects
- ✅ Executed **functional, regression, integration, system, and user acceptance testing (UAT)** across multiple releases
- 🔗 Provided continuous **technical QA support** throughout the SDLC, collaborating closely with developers, product owners, and stakeholders

---

## Tools & Technologies

- **Automation:** Playwright, TypeScript, JavaScript
- **CI/CD & Cloud:** Azure DevOps, Microsoft Azure
- **QA & Planning:** Test Planning, Test Design, monday.com
- **Methodologies:** Agile, SDLC

---

## Skills & Competencies

- Test Automation & Framework Design
- End-to-End QA Ownership
- CI/CD Integration for Testing
- Manual & Exploratory Testing
- Regression & UAT Testing
- Agile Collaboration
- Problem Solving & Analytical Thinking
- Web Application Quality Assurance

---

## Impact
This role allowed me to transition into a more **automation- and infrastructure-focused QA position**, delivering scalable testing solutions, improving release confidence, and embedding quality deeply into the CI/CD pipeline.`,
        },
        {
          title: 'QA Engineer',
          company: 'Tudip Technologies',
          description: 'Led comprehensive quality assurance across web and mobile platforms, developing BDD test cases with Selenium and Python integrated into Jenkins CI, while performing functional, regression, and API testing.',
          detailContent: `# QA Engineer – Tudip Technologies (Contract)

**Period:** Mar 2022 – Dec 2023 (1 yr 10 mos)  
**Location:** Pune, Maharashtra, India · Remote  
**Role Type:** Contract

---

## Role Overview
As a **QA Engineer** at **Tudip Technologies**, I led comprehensive quality assurance efforts for web and mobile applications, working across multiple clients and projects while building foundational test automation expertise.

---

## Key Responsibilities & Contributions

- 📋 Reviewed **functional and design specifications** to align testing objectives with project requirements and deliverables
- 🧪 Developed and executed **detailed test cases** for various functionalities across **web, Android, and iOS platforms**
- 🤖 Collaborated with a Senior QA Engineer to design and develop **test cases using Gherkin (BDD)** and **Selenium with Python**, integrating them into a **Jenkins CI pipeline**
- ✅ Performed **functional, regression, integration, and accessibility testing**
- 🔗 Utilized **Postman** for comprehensive **REST API testing**
- 👥 Mentored new hires and led multiple onboarding processes

---

## Tools & Technologies

- **Automation:** Selenium, Python, Gherkin (BDD)
- **CI/CD:** Jenkins
- **Testing Tools:** Postman, SoapUI, TestRail
- **Management:** Jira, Agile, Scrum
- **Platforms:** Web, Android, iOS

---

## Skills & Competencies

- Cross-Platform Testing (Web, iOS, Android)
- API Testing & Validation
- Test Automation with Selenium
- BDD Test Design (Gherkin)
- CI Integration (Jenkins)
- Functional & Regression Testing
- Mentoring & Team Collaboration
- Problem Solving & Analytical Thinking

---

## Impact
This role strengthened my ability to work in fast-paced Agile teams, ensured consistent software quality across multiple platforms, and allowed me to mentor new team members while contributing to reliable and scalable testing processes.`,
        },
      ],
    },
    footer: {
      heading: 'Let\'s Connect',
      subheading: 'Interested in working together? Feel free to reach out!',
      legalNotice: 'Legal Notice',
      copyright: '© 2026 Francisco Perez Leiros. All rights reserved.',
      legalModal: {
        owner: 'Owner',
        legalStatus: 'Legal Status',
        legalStatusText: 'Freelance professional (Partita IVA – Italy)',
        vatNumber: 'VAT Number (Partita IVA)',
        taxCode: 'Tax Code (Codice Fiscale)',
        registeredOffice: 'Registered Office',
        registeredOfficeText: 'Verona, Italy',
        contact: 'Contact',
        contactEmail: 'Email: fran.pl@icloud.com',
        privacy: 'Privacy',
        privacyText: 'This website does not collect personal data except for information voluntarily provided via email contact.',
      },
    },
    skills: {
      ai: {
        name: 'AI',
        description: 'Leveraging AI to enhance quality engineering workflows — from smarter test design to improved analysis, productivity, and automation efficiency.',
      },
      mcps: {
        name: 'MCP\'s',
        description: 'Designing and applying Playwright MCP and Model Context Protocols to improve test orchestration, maintainability, and scalable automation architectures.',
      },
      testAutomation: {
        name: 'Test Automation',
        description: 'Architecting and implementing scalable test automation frameworks that reduce regression effort and ensure consistent product quality.',
      },
      pipelineDesign: {
        name: 'Pipeline Design',
        description: 'Building and integrating CI/CD pipelines that enable continuous testing and fast feedback using Azure DevOps and GitHub Actions.',
      },
      agileScrum: {
        name: 'Agile/Scrum',
        description: 'Collaborating in Agile and Scrum teams to align testing strategies with business goals and deliver value incrementally.',
      },
      e2eTesting: {
        name: 'E2E Testing',
        description: 'Validating complete user flows across front-end and backend systems to guarantee reliability in real production-like scenarios.',
      },
      regressionTesting: {
        name: 'Regression Testing',
        description: 'Designing efficient regression strategies combining automation and manual validation to protect critical functionality on every release.',
      },
      apiTesting: {
        name: 'API testing',
        description: 'Validating REST APIs for correctness, performance, and data integrity using Postman and automated test frameworks.',
      },
      mobileTesting: {
        name: 'Mobile Testing',
        description: 'Testing mobile applications across iOS and Android platforms to ensure functionality, usability, and cross-device consistency.',
      },
      playwright: {
        name: 'Playwright',
        description: 'Using Playwright with TypeScript to build fast, modern, and reliable end-to-end automation frameworks for web applications.',
      },
      selenium: {
        name: 'Selenium',
        description: 'Applying Selenium with Python for cross-browser automation and integration into CI pipelines in legacy and hybrid test environments.',
      },
      typescript: {
        name: 'TypeScript',
        description: 'Writing clean, maintainable TypeScript code to improve test reliability, readability, and long-term framework scalability.',
      },
      python: {
        name: 'Python',
        description: 'Utilizing Python for test automation, API validation, data analysis, and system-level testing scenarios.',
      },
      docker: {
        name: 'Docker',
        description: 'Containerizing test environments and applications using Docker to ensure consistent execution across local and CI environments.',
      },
      azureDevOps: {
        name: 'Azure DevOps',
        description: 'Managing CI/CD pipelines, test automation, and release workflows in Azure DevOps to ensure quality gates and fast feedback.',
      },
      githubActions: {
        name: 'GitHub Actions',
        description: 'Building automated workflows and CI/CD pipelines using GitHub Actions for continuous integration and deployment.',
      },
      jira: {
        name: 'Jira',
        description: 'Tracking defects, test activities, and sprint progress to ensure transparency and alignment across teams.',
      },
      postman: {
        name: 'Postman',
        description: 'Designing and executing API test collections to validate backend services independently from the UI.',
      },
    },
  },
  es: {
    nav: {
      about: 'Sobre mí',
      experience: 'Experiencia',
      projects: 'Proyectos',
      contact: 'Contacto',
    },
    hero: {
      greeting: 'Hola, soy',
      name: 'Francisco Perez Leiros',
      title: 'Ingeniero de QA de Software',
      tagline: 'Especializado en Automatización de Pruebas, CI/CD, integración de IA y Aseguramiento de Calidad para sistemas web, móviles, cloud e industriales.',
      downloadCV: 'Descargar CV',
      getInTouch: 'Contactar',
      viewWork: 'Ver mi trabajo',
      downloadEnglish: 'Versión en Inglés',
      downloadSpanish: 'Versión en Español',
    },
    about: {
      heading: 'Sobre Mí',
      paragraphs: [
        'Ingeniero de QA de Automatización con más de 5 años de experiencia en sistemas web, móviles, cloud e industriales. Sólida experiencia en pruebas manuales, con una clara progresión hacia la automatización de pruebas, integración CI/CD y aseguramiento de calidad a nivel de sistema.',
        'Actualmente trabajo como Ingeniero de Pruebas de Aseguramiento de Calidad de Software en Tetra Pak, realizando Verificación y Validación (V&V) de soluciones de automatización industrial utilizando PLCs Beckhoff y TwinCAT. Mi trabajo incluye pruebas a nivel de sistema en entornos Linux (CentOS) desplegados en la nube, validación de requisitos funcionales y de seguridad, y análisis de logs basados en SQL para apoyar el análisis de causa raíz y la resolución de defectos.',
        'Anteriormente en Cemantica, supervisé el proceso de QA de principio a fin y construí frameworks de automatización utilizando Playwright (incluyendo MCP) con TypeScript, completamente integrado en pipelines CI/CD de Azure DevOps. Esto permitió pruebas de regresión automatizadas y mejoró la confiabilidad de los lanzamientos.',
        'Al inicio de mi carrera, construí sólidos fundamentos de QA a través de pruebas manuales prácticas, API y pruebas multiplataforma en aplicaciones web y móviles, trabajando en entornos Agile/Scrum y colaborando estrechamente con desarrolladores y equipos de producto.',
      ],
    },
    experience: {
      heading: 'Experiencia Profesional',
      jobs: [
        {
          role: 'Especialista en Pruebas de Garantía de Calidad',
          company: 'Tetrapak - Módena, Italia',
          duration: '11/2024 - 11/2025',
          description: 'Realicé Verificación y Validación (V&V) de planes de prueba y redacté casos de prueba exhaustivos para sistemas de automatización industrial usando PLCs Beckhoff y TwinCAT, con casos de prueba escritos en Gherkin (BDD) para especificaciones claras y orientadas al comportamiento. Ejecuté pruebas de sistema desplegados usando Docker en plataformas Cloud sobre entornos Linux basados en CentOS, asegurando el cumplimiento de requisitos funcionales y de seguridad. Analicé e interpreté datos de registro basados en SQL generados por sistemas de automatización para verificar el comportamiento del sistema, solucionar problemas y apoyar el análisis de causa raíz.',
        },
        {
          role: 'Especialista en Garantía de Calidad',
          company: 'Cemantica - París, Francia',
          duration: '12/2023 - 11/2024',
          description: 'Gestioné el proceso completo de QA, incluyendo el desarrollo de suites de prueba integrales y la ejecución de pruebas funcionales, de regresión e integración. Diseñé un marco de automatización de pruebas desde cero usando TypeScript y Playwright, integrado directamente en pipelines de Azure DevOps para ejecuciones automatizadas. También usé GitHub y GitHub Actions. Ejecuté una estrategia de pruebas híbrida, utilizando scripts automatizados para regresión mientras realizaba pruebas manuales para casos extremos y validación de UI/UX. Actué como el principal punto de contacto técnico para la resolución de defectos, depurando para ayudar al equipo de desarrollo a corregir errores de alta prioridad.',
        },
        {
          role: 'Ingeniero de QA',
          company: 'Tudip Technologies - Pune, India',
          duration: '03/2022 - 12/2023',
          description: 'Revisé especificaciones funcionales y de diseño para alinear objetivos de prueba con requisitos del proyecto. Desarrollé y ejecuté casos de prueba detallados para diversas funcionalidades en plataformas web y móviles (iOS y Android). Colaboré con un Ingeniero Senior de QA para diseñar y desarrollar casos de prueba usando Gherkin (BDD) y Selenium con Python, integrándolos en un pipeline CI de Jenkins. Realicé diversos tipos de pruebas, incluyendo pruebas funcionales, de regresión, integración y accesibilidad. Usé Postman para pruebas exhaustivas de API REST. Mentoricé a nuevos empleados, liderando múltiples procesos de incorporación.',
        },
        {
          role: 'Tester de QA',
          company: 'UTest - Massachusetts, Estados Unidos',
          duration: '11/2020 - 03/2022',
          description: 'Realicé pruebas manuales de plataformas basadas en web, desarrollando planes y casos de prueba detallados. Ejecuté pruebas funcionales, de regresión, integración y aceptación de usuario para asegurar la estabilidad de la plataforma. Colaboré con equipos para validar nuevas características e identificar errores críticos.',
        },
      ],
    },
    portfolio: {
      heading: 'Proyectos Destacados',
      viewDetails: 'Ver detalles completos',
      projects: [
        {
          title: 'Ingeniero de Pruebas de Garantía de Calidad de Software',
          company: 'Tetra Pak',
          description: 'Realicé Verificación y Validación para sistemas de automatización industrial usando PLCs Beckhoff, incluyendo pruebas a nivel de sistema en entornos Linux desplegados en la nube y análisis de registros basados en SQL para resolución de causa raíz.',
          detailContent: `# Ingeniero de Pruebas de Garantía de Calidad de Software – Tetra Pak (Contrato)

**Periodo:** Nov 2024 – Nov 2025 (1 año 1 mes)  
**Ubicación:** Módena, Emilia-Romaña, Italia · Híbrido  
**Tipo de Función:** Contrato

---

## Descripción de la Función
Como **Ingeniero de Pruebas de Garantía de Calidad de Software** en **Tetra Pak**, trabajé en sistemas de automatización industrial y basados en la nube, enfocándome en **Verificación y Validación (V&V)**, pruebas a nivel de sistema y análisis de calidad basado en datos en entornos complejos y críticos para la seguridad.

---

## Responsabilidades Clave y Contribuciones

- 🏭 Realicé **Verificación y Validación (V&V)** para sistemas de automatización industrial usando **PLCs Beckhoff y TwinCAT**, asegurando el cumplimiento de requisitos funcionales y de seguridad
- 🧪 Redacté y ejecuté **casos de prueba a nivel de sistema** cubriendo lógica de control, integraciones del sistema y escenarios extremos
- ☁️ Realicé **pruebas de sistema en entornos Linux (CentOS) desplegados en la nube**, validando estabilidad, confiabilidad y comportamiento operacional del mundo real
- 🗄️ Analicé **datos de registro basados en SQL** para verificar el comportamiento del sistema, apoyar el análisis de causa raíz y acelerar la resolución de defectos
- 🔗 Colaboré estrechamente con **equipos de ingeniería multifuncionales** usando **Azure DevOps** para seguimiento de defectos, ejecución de pruebas y mejora continua de calidad

---

## Herramientas y Tecnologías

- **Automatización Industrial:** Beckhoff PLC, TwinCAT
- **Cloud e Infraestructura:** Microsoft Azure, Docker, Linux (CentOS)
- **Datos y Análisis:** SQL
- **QA y ALM:** Azure DevOps
- **Prácticas de Pruebas:** Planificación de Pruebas, Diseño de Pruebas, Pruebas de Integración y Sistema

---

## Habilidades y Competencias

- Verificación y Validación (V&V)
- Pruebas de Sistema e Integración
- QA de Automatización Industrial
- Pruebas de Sistemas Basados en Cloud
- Análisis de Logs e Investigación de Causa Raíz
- Colaboración Multifuncional
- Garantía de Calidad en Sistemas Críticos para la Seguridad

---

## Impacto
Este rol fortaleció mi experiencia en **garantía de calidad industrial y a nivel de sistema**, conectando software, infraestructura cloud y sistemas de automatización para asegurar confiabilidad, seguridad y trazabilidad en entornos críticos de producción.`,
        },
        {
          title: 'Especialista en Garantía de Calidad',
          company: 'Cemantica',
          description: 'Diseñé e implementé marcos de prueba automatizados usando Playwright con TypeScript, construí un pipeline CI/CD completo desde cero integrado con Azure DevOps, permitiendo la ejecución automatizada de pruebas dentro del pipeline de entrega.',
          detailContent: `# Especialista en Garantía de Calidad – Cemantica (Contrato)

**Periodo:** Dic 2023 – Nov 2024 (1 año)  
**Ubicación:** Levallois-Perret, Isla de Francia, Francia · Remoto  
**Tipo de Función:** Contrato

---

## Descripción de la Función
Como **Especialista en Garantía de Calidad** en **Cemantica**, tuve la responsabilidad del ciclo de vida completo de QA para el producto, combinando una fuerte gestión de estrategia de pruebas con automatización práctica, integración de CI/CD y pruebas manuales para asegurar calidad consistente en todos los lanzamientos.

---

## Responsabilidades Clave y Contribuciones

- 🧠 Gestioné el **proceso de QA de extremo a extremo**, incluyendo definición de estrategia de pruebas, planificación, ejecución y validación de lanzamientos
- 🤖 Diseñé e implementé **frameworks de pruebas automatizadas** usando **Playwright con TypeScript**, aumentando significativamente la cobertura de pruebas de regresión
- 🚀 Construí un **pipeline CI/CD desde cero** integrado con **Azure DevOps**, permitiendo la ejecución automatizada de pruebas dentro del pipeline de entrega
- 🧪 Realicé **pruebas manuales y exploratorias** para complementar la automatización e identificar defectos en casos extremos
- ✅ Ejecuté **pruebas funcionales, de regresión, integración, sistema y aceptación de usuario (UAT)** en múltiples lanzamientos
- 🔗 Proporcioné **soporte técnico continuo de QA** durante todo el SDLC, colaborando estrechamente con desarrolladores, propietarios de producto y stakeholders

---

## Herramientas y Tecnologías

- **Automatización:** Playwright, TypeScript, JavaScript
- **CI/CD y Cloud:** Azure DevOps, Microsoft Azure
- **QA y Planificación:** Planificación de Pruebas, Diseño de Pruebas, monday.com
- **Metodologías:** Agile, SDLC

---

## Habilidades y Competencias

- Automatización de Pruebas y Diseño de Frameworks
- Propiedad de QA de Extremo a Extremo
- Integración CI/CD para Pruebas
- Pruebas Manuales y Exploratorias
- Pruebas de Regresión y UAT
- Colaboración Ágil
- Resolución de Problemas y Pensamiento Analítico
- Garantía de Calidad de Aplicaciones Web

---

## Impacto
Este rol me permitió transicionar a una **posición de QA más enfocada en automatización e infraestructura**, entregando soluciones de pruebas escalables, mejorando la confianza en los lanzamientos e integrando la calidad profundamente en el pipeline CI/CD.`,
        },
        {
          title: 'Ingeniero de QA',
          company: 'Tudip Technologies',
          description: 'Lideré la garantía de calidad exhaustiva en plataformas web y móviles, desarrollando casos de prueba BDD con Selenium y Python integrados en Jenkins CI, mientras realizaba pruebas funcionales, de regresión y de API.',
          detailContent: `# Ingeniero de QA – Tudip Technologies (Contrato)

**Periodo:** Mar 2022 – Dic 2023 (1 año 10 meses)  
**Ubicación:** Pune, Maharashtra, India · Remoto  
**Tipo de Función:** Contrato

---

## Descripción de la Función
Como **Ingeniero de QA** en **Tudip Technologies**, lideré esfuerzos exhaustivos de garantía de calidad para aplicaciones web y móviles, trabajando en múltiples clientes y proyectos mientras construía experiencia fundamental en automatización de pruebas.

---

## Responsabilidades Clave y Contribuciones

- 📋 Revisé **especificaciones funcionales y de diseño** para alinear objetivos de pruebas con requisitos y entregables del proyecto
- 🧪 Desarrollé y ejecuté **casos de prueba detallados** para diversas funcionalidades en **plataformas web, Android e iOS**
- 🤖 Colaboré con un Ingeniero Senior de QA para diseñar y desarrollar **casos de prueba usando Gherkin (BDD)** y **Selenium con Python**, integrándolos en un **pipeline CI de Jenkins**
- ✅ Realicé **pruebas funcionales, de regresión, integración y accesibilidad**
- 🔗 Utilicé **Postman** para **pruebas exhaustivas de API REST**
- 👥 Mentoricé a nuevos empleados y lideré múltiples procesos de incorporación

---

## Herramientas y Tecnologías

- **Automatización:** Selenium, Python, Gherkin (BDD)
- **CI/CD:** Jenkins
- **Herramientas de Pruebas:** Postman, SoapUI, TestRail
- **Gestión:** Jira, Agile, Scrum
- **Plataformas:** Web, Android, iOS

---

## Habilidades y Competencias

- Pruebas Multiplataforma (Web, iOS, Android)
- Pruebas y Validación de API
- Automatización de Pruebas con Selenium
- Diseño de Pruebas BDD (Gherkin)
- Integración CI (Jenkins)
- Pruebas Funcionales y de Regresión
- Mentoría y Colaboración en Equipo
- Resolución de Problemas y Pensamiento Analítico

---

## Impacto
Este rol fortaleció mi capacidad para trabajar en equipos Ágiles de ritmo rápido, aseguró calidad de software consistente en múltiples plataformas, y me permitió mentorar a nuevos miembros del equipo mientras contribuía a procesos de pruebas confiables y escalables.`,
        },
      ],
    },
    footer: {
      heading: 'Conectemos',
      subheading: '¿Interesado en trabajar juntos? ¡No dudes en contactarme!',
      legalNotice: 'Aviso Legal',
      copyright: '© 2026 Francisco Perez Leiros. Todos los derechos reservados.',
      legalModal: {
        owner: 'Propietario',
        legalStatus: 'Estado Legal',
        legalStatusText: 'Profesional independiente (Partita IVA – Italia)',
        vatNumber: 'Número de IVA (Partita IVA)',
        taxCode: 'Código Fiscal (Codice Fiscale)',
        registeredOffice: 'Oficina Registrada',
        registeredOfficeText: 'Verona, Italia',
        contact: 'Contacto',
        contactEmail: 'Email: fran.pl@icloud.com',
        privacy: 'Privacidad',
        privacyText: 'Este sitio web no recopila datos personales excepto la información proporcionada voluntariamente a través del contacto por correo electrónico.',
      },
    },
    skills: {
      ai: {
        name: 'IA',
        description: 'Aprovechando la IA para mejorar los flujos de trabajo de ingeniería de calidad — desde diseño de pruebas más inteligente hasta un análisis, productividad y eficiencia de automatización mejorados.',
      },
      mcps: {
        name: 'MCP\'s',
        description: 'Diseñando y aplicando Playwright MCP y Model Context Protocols para mejorar la orquestación de pruebas, mantenibilidad y arquitecturas de automatización escalables.',
      },
      testAutomation: {
        name: 'Automatización de Pruebas',
        description: 'Arquitectando e implementando frameworks de automatización de pruebas escalables que reducen el esfuerzo de regresión y aseguran calidad consistente del producto.',
      },
      pipelineDesign: {
        name: 'Diseño de Pipelines',
        description: 'Construyendo e integrando pipelines CI/CD que permiten pruebas continuas y retroalimentación rápida usando Azure DevOps y GitHub Actions.',
      },
      agileScrum: {
        name: 'Agile/Scrum',
        description: 'Colaborando en equipos Agile y Scrum para alinear estrategias de pruebas con objetivos de negocio y entregar valor incrementalmente.',
      },
      e2eTesting: {
        name: 'Pruebas E2E',
        description: 'Validando flujos de usuario completos a través de sistemas frontend y backend para garantizar confiabilidad en escenarios similares a producción.',
      },
      regressionTesting: {
        name: 'Pruebas de Regresión',
        description: 'Diseñando estrategias de regresión eficientes combinando automatización y validación manual para proteger funcionalidad crítica en cada lanzamiento.',
      },
      apiTesting: {
        name: 'Pruebas de API',
        description: 'Validando APIs REST para corrección, rendimiento e integridad de datos usando Postman y frameworks de pruebas automatizadas.',
      },
      mobileTesting: {
        name: 'Pruebas Móviles',
        description: 'Probando aplicaciones móviles en plataformas iOS y Android para asegurar funcionalidad, usabilidad y consistencia entre dispositivos.',
      },
      playwright: {
        name: 'Playwright',
        description: 'Usando Playwright con TypeScript para construir frameworks de automatización end-to-end rápidos, modernos y confiables para aplicaciones web.',
      },
      selenium: {
        name: 'Selenium',
        description: 'Aplicando Selenium con Python para automatización cross-browser e integración en pipelines CI en entornos de prueba legacy e híbridos.',
      },
      typescript: {
        name: 'TypeScript',
        description: 'Escribiendo código TypeScript limpio y mantenible para mejorar la confiabilidad de las pruebas, legibilidad y escalabilidad del framework a largo plazo.',
      },
      python: {
        name: 'Python',
        description: 'Utilizando Python para automatización de pruebas, validación de API, análisis de datos y escenarios de pruebas a nivel de sistema.',
      },
      docker: {
        name: 'Docker',
        description: 'Contenerizando entornos de prueba y aplicaciones usando Docker para asegurar ejecución consistente en entornos locales y de CI.',
      },
      azureDevOps: {
        name: 'Azure DevOps',
        description: 'Gestionando pipelines CI/CD, automatización de pruebas y flujos de lanzamiento en Azure DevOps para asegurar puertas de calidad y retroalimentación rápida.',
      },
      githubActions: {
        name: 'GitHub Actions',
        description: 'Construyendo flujos de trabajo automatizados y pipelines CI/CD usando GitHub Actions para integración y despliegue continuo.',
      },
      jira: {
        name: 'Jira',
        description: 'Rastreando defectos, actividades de prueba y progreso de sprints para asegurar transparencia y alineación entre equipos.',
      },
      postman: {
        name: 'Postman',
        description: 'Diseñando y ejecutando colecciones de pruebas de API para validar servicios backend independientemente de la UI.',
      },
    },
  },
};
