// src/components/Experience.tsx
import React from 'react';
import styles from './Experience.module.css';

const experiences = [
  {
    role: "Quality Assurance Test Specialist",
    company: "Tetrapak - Modena, Italy",
    duration: "11/2024 - 11/2025",
    description: "Performed Verification and Validation (V&V) of test plans and authored comprehensive test cases for industrial automation systems using Beckhoff and TwinCAT PLCs, with test cases written in Gherkin (BDD) for clear, behavior-driven specifications. Conducted system testing deployed using Docker across Cloud platforms on Linux CentOS-based environments, ensuring compliance with functional and safety requirements. Analysed and interpreted SQL-based log data generated by automation systems to verify system behaviour, troubleshoot issues, and support root cause analysis."
  },
  {
    role: "Quality Assurance Specialist",
    company: "Cemantica - Paris, France",
    duration: "12/2023 - 11/2024",
    description: "Managed the full QA process, including the development of comprehensive test suites and the execution of functional, regression, and integration tests. Engineered a test automation framework from scratch using TypeScript and Playwright, integrated directly into Azure DevOps pipelines for automated runs. Also used GitHub and GitHub Actions. Executed a hybrid testing strategy, utilizing automated scripts for regression while performing manual testing for edge cases and UI/UX validation. Acted as the primary technical point of contact for defect resolution, debugging to assist the development team in fixing high-priority bugs."
  },
  {
    role: "QA Engineer",
    company: "Tudip Technologies - Pune, India",
    duration: "03/2022 - 12/2023",
    description: "Reviewed functional and design specifications to align testing objectives with project requirements. Developed and executed detailed test cases for various functionalities across web and mobile platforms (iOS & Android). Collaborated with a Senior QA Engineer to design and develop test cases using Gherkin (BDD) and Selenium with Python, integrating them into a Jenkins CI pipeline. Performed diverse testing types, including functional, regression, integration, and accessibility testing. Used Postman for comprehensive REST API testing. Mentored new hires, leading multiple onboarding processes."
  },
  {
    role: "QA Tester",
    company: "UTest - Massachusetts, United States",
    duration: "11/2020 - 03/2022",
    description: "Conducted manual testing of web-based platforms, developing detailed test plans and cases. Performed functional, regression, integration, and user acceptance testing to ensure platform stability. Collaborated with teams to validate new features and identify critical bugs."
  }
];

const Experience: React.FC = () => {
  return (
    <section id="experience" className={styles.experience}>
      <div className="container">
        <h2 className={styles.heading}>Professional Experience</h2>
        <div className={styles.timeline}>
          {experiences.map((exp, index) => (
            <div key={index} className={styles.timelineItem}>
              <div className={styles.timelineContent}>
                <h3>{exp.role}</h3>
                <h4 className={styles.company}>{exp.company}</h4>
                <span className={styles.duration}>{exp.duration}</span>
                <ul>
                  {exp.description.split('. ').map((sentence, i) => (
                    sentence && <li key={i}><span className={styles.bulletPoint}></span>{sentence}.</li>
                  ))}
                </ul>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Experience;
